Improve preflight file permissions check (#114)
* Added startup permissions check with more helpful message

* Updated README

* Fixes faulty test

diff --git a/rel/overlays/bin/docker_start b/rel/overlays/bin/docker_start
--- a/rel/overlays/bin/docker_start
+++ b/rel/overlays/bin/docker_start
@@ -1,4 +1,11 @@
 #!/bin/sh
+/app/bin/check_file_permissions
+
+if [ $? -ne 0 ]; then
+  echo "Filesystem error. Exiting."
+  exit 1
+fi
+
 /app/bin/migrate
 
 cd -P -- "$(dirname -- "$0")"
